### ISSUE TITLE
Task: Understanding CI/CD by doing from development to testing

### ISSUE THREAD

**Issue by Jahidul2543** [IzaanSchool/B2301-EventApp#2]
### Task

1.  Clone the repo https://github.com/IzaanSchool/B2301-EventApp
2. Create a branch named feature/your-github-user-name
3. Make some changes in the index.html code
4. Push the new branch in the repo.
5. Let us know what you see in Izaan School AWS Account Amplify

Based on your work and research study please let us know what do you understand by CI/CD. You can write all your findings here as comments.

### What did we learn from the exercise? (Update)

- [ ] How to create a feature branch?
- [ ] Why create a feature branch?
- [ ] How to make a pull request?
- [ ] What is the branch protection role in GitHub?
- [ ] How can we mandatorily enforce code reviewers to approve a pull request?
- [ ] What is Code Review?
- [ ] How is a GitHub branch connected with an Amplify Environment?
- [ ] How does automatically amplify starts provisioning, building, and deploying new changes in the hosting environment?
- [ ] Current amplify environment is missing the automated testing stage. Thus this can not be named a complete CI/CD environment.

**Comment by taneeza** [comment]
@Jahidul2543 ,
I was trying to push the new feature branch but it is showing me the following message 
"remote: Permission to IzaanSchool/B2301-EventApp.git denied to taneeza.
fatal: unable to access 'https://github.com/IzaanSchool/B2301-EventApp.git/': The requested URL returned error: 403
"

**Comment by Jahidul2543** [comment]
Can you check which branch you are trying to push?
Share a complete screenshot of the terminal

**Comment by taneeza** [comment]
> Can you check which branch you are trying to push? Share a complete screenshot of the terminal
<img width="960" alt="image" src="https://github.com/IzaanSchool/B2301-EventApp/assets/127346395/e1eacc91-8661-41fb-aee2-6775542b4370">

**Comment by shejutiqa** [comment]
I pushed  the feature branch successfully. I made a little bit change .

**Comment by AyshaShetu** [comment]
Changes : 1) Heading Color Red
                 2) Picnic Activities (instead of About the Picnic)
![image](https://github.com/IzaanSchool/B2301-EventApp/assets/127298305/0c632e49-ac4c-42fb-b499-20c78e44303c)

**Comment by sarah-kh** [comment]
https://github.com/IzaanSchool/B2301-EventApp/tree/feature_Sarah

made some changes

**Comment by Jahidul2543** [comment]
> Changes : 1) Heading Color Red
> 
>                  2) Picnic Activities (instead of About the Picnic)
> 
> ![image](https://github.com/IzaanSchool/B2301-EventApp/assets/127298305/0c632e49-ac4c-42fb-b499-20c78e44303c)
> 
> 

Push your branch in the repo

**Comment by taneeza** [comment]
https://docs.google.com/document/d/1eAiOwdvjDqRoDKsv-c2vXEEP41ZMVlV7BpXkg4W-lco/edit?usp=sharing

My work is not finished. I just tried to read articles from some websites and understand the CI/CD. I just took some notes. My apology for my clumsy work.

**Comment by AyshaShetu** [comment]
https://docs.google.com/document/d/1KMvu_OZEQZvfbSAXy2UYZEHqLJdI8X-JIUeKWzZtNXQ/edit?usp=sharing
I was trying to take note about what we have learned from yesterday's class. it's not final, still on process. need to add /delete information there to get the perfect answer but trying to write a brief conception on those topics .so that if we are asked questions on these stuffs, we can talk and cover important points.  You can help and suggest making the answer look more acceptable.
